#------ CHROME DRIVER---
[drivers]
chrome_path = ..//Driver//chromedriver.exe
 #138.0.7204.101


# ---- URL ---\
[url]
url = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login

# ---- Login Cred ---
[login]
usernam = Admin
paasword = admin123


#----- EXCEL PATH ----
[excel_path]
theme_dashboard_xlsx = ..//Databuilder//Input//ORMTheme_v1
pdf_file_path = ..TestData//Uploads//
txt_file_path = ..TestData//Uploads//
xlsx_file_path = ..TestData//Uploads//
doc_file_path = ..TestData//Uploads//
docx_file_path = ..TestData//Uploads//
xls_file_path = ..TestData//Uploads//

orm_actual_file_path = ..TestData//Uploads//

validation_l1_xlsx = ..//ComparisonUtility//Validation_L1_xlsx
validation_l2_xlsx = ..//ComparisonUtility//Validation_L2_xlsx
validation_l3_xlsx = ..//ComparisonUtility//Validation_L3_xlsx

#------- ELK SEARCH----
[CREDENTIALS]
username = elk-cash-automation-preprod
password = asdfghjgfd

[INDEXNAME]
index_name = elk-cash-automation-preprod

[ELKURL]
elk_url = https://deceldvpapppprs.preprod-logging.deveops.idfcbank.com:9200

#----STATIC_FOLDER_PATH------
[static_folder_path]
image_folder_path = ../TestData/image/
screenshot_folder_path = ../TestData/Screenshot/
logger = ..//Logs//logs.log
image_processing_output_folder = ../TestData/ORM_IMAGE_PROCESSING_OUTPUT/OUTPUT/

#----ECXEL_SHEET___
[excel_sheet]
initiate = ORM_init

#----SHEET_NAME__
[sheet_name]
child_sheet_name = Account_info

